name: Publish to AUR

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  aur:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: neurafly
          pkgbuild: packaging/aur/PKGBUILD
          commit_username: Emiliano Gandini Outeda
          commit_email: emiliano.gandini@protonmail.com
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to ${{ github.ref_name }}"
